[package]
name = "cargo-nuget"
version = "0.1.0"
authors = ["Wahid Morian <wmorian@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
